import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "~/layouts/header/Header";

/* This provider is only used to avoid hydratation and compatibility errors with nextjs
 * ref: https://mui.com/material-ui/integrations/nextjs/#app-router
 */
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { SurvivorAuthProvider } from "~/contexts/SurvivorContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SurvivorAuthProvider>
          <AppRouterCacheProvider>
            <Header/>

            <div className="px-2 py-12 sm:px-32">
              {children}
            </div>
          </AppRouterCacheProvider>
        </SurvivorAuthProvider>
      </body>
    </html>
  );
}
