services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:3000"
    expose:
      - "3000"
    command: "yarn dev"
    depends_on:
      - backend
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    expose:
      - "3000"
    command: "yarn start"
    env_file:
     - ./backend/.env
    depends_on:
      - pg-database
  pg-database:
    image: postgres:latest
    volumes:
        - pgdata:/var/lib/postgresql/data
    ports:
     - "5437:5432"
    env_file:
     - ./backend/.env

volumes:
  pgdata: