services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "8080:8080"
    networks:
      - nexus_network
    env_file:
    - ./frontend/.env
    expose:
      - "8080"
    command: "yarn dev"
    depends_on:
      - backend
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - nexus_network
    expose:
      - "3000"
    command: "yarn start"
    env_file:
     - ./backend/.env
    depends_on:
      - pg-database
  pg-database:
    image: postgres:latest
    volumes:
        - pgdata:/var/lib/postgresql/data
    ports:
     - "5437:5432"
    networks:
      - nexus_network
    env_file:
     - ./backend/.env

networks:
  nexus_network:
    driver: bridge

volumes:
  pgdata:
